export interface NutritionEntry {
  matches: string[]
  nameEn: string
  protein: number
  fat: number
  carbs: number
  sugar?: number
  fiber?: number
  calories: number
  measureType: 'gram' | 'unit'
  unitName?: string
  unitGrams?: number
  preparation?: 'crudo' | 'cocido'
}

export const NUTRITION_DATA: NutritionEntry[] = [
  { matches: ['huevo', 'huevos'], nameEn: 'Egg', protein: 13, fat: 11, carbs: 1.1, sugar: 1.1, fiber: 0, calories: 155, measureType: 'unit', unitName: 'huevo', unitGrams: 60, preparation: 'crudo' },
  { matches: ['atun', 'atún'], nameEn: 'Tuna', protein: 26, fat: 1, carbs: 0, sugar: 0, fiber: 0, calories: 116, measureType: 'gram', preparation: 'crudo' },
  { matches: ['queso', 'quesos'], nameEn: 'Cheese', protein: 25, fat: 33, carbs: 1.3, sugar: 1.3, fiber: 0, calories: 402, measureType: 'gram', preparation: 'crudo' },
  { matches: ['cerdo'], nameEn: 'Pork', protein: 21, fat: 10, carbs: 0, sugar: 0, fiber: 0, calories: 180, measureType: 'gram', preparation: 'crudo' },
  { matches: ['res', 'carne de res', 'molida de res'], nameEn: 'Beef', protein: 26, fat: 15, carbs: 0, sugar: 0, fiber: 0, calories: 242, measureType: 'gram', preparation: 'crudo' },
  { matches: ['yogurt griego', 'yogur griego'], nameEn: 'Greek Yogurt', protein: 10, fat: 3, carbs: 4, sugar: 4, fiber: 0, calories: 97, measureType: 'gram', preparation: 'crudo' },
  { matches: ['salmon', 'salmón'], nameEn: 'Salmon', protein: 20, fat: 13, carbs: 0, sugar: 0, fiber: 0, calories: 208, measureType: 'gram', preparation: 'crudo' },
  { matches: ['pescado blanco', 'tilapia', 'mero'], nameEn: 'White Fish', protein: 20, fat: 1.7, carbs: 0, sugar: 0, fiber: 0, calories: 96, measureType: 'gram', preparation: 'crudo' },
  { matches: ['pechuga de pavo', 'pavo'], nameEn: 'Turkey Breast', protein: 22, fat: 1.6, carbs: 0, sugar: 0, fiber: 0, calories: 104, measureType: 'gram', preparation: 'crudo' },
  { matches: ['jamon de pavo', 'jamón de pavo'], nameEn: 'Turkey Ham', protein: 19, fat: 3, carbs: 2, sugar: 1, fiber: 0, calories: 110, measureType: 'gram', preparation: 'crudo' },
  { matches: ['claras de huevo', 'clara de huevo'], nameEn: 'Egg White', protein: 11, fat: 0.2, carbs: 0.7, sugar: 0.7, fiber: 0, calories: 52, measureType: 'gram', preparation: 'crudo' },
  { matches: ['cottage cheese', 'requeson', 'requesón'], nameEn: 'Cottage Cheese', protein: 11, fat: 4.3, carbs: 3.4, sugar: 2.7, fiber: 0, calories: 98, measureType: 'gram', preparation: 'crudo' },
  { matches: ['salchicha', 'salchichas'], nameEn: 'Sausage', protein: 13, fat: 18, carbs: 1, sugar: 1, fiber: 0, calories: 215, measureType: 'gram', preparation: 'crudo' },
  { matches: ['chorizo'], nameEn: 'Chorizo', protein: 13, fat: 27, carbs: 2, sugar: 0, fiber: 0, calories: 300, measureType: 'gram', preparation: 'crudo' },
  { matches: ['tocino', 'bacon'], nameEn: 'Bacon', protein: 14, fat: 42, carbs: 1, sugar: 0, fiber: 0, calories: 417, measureType: 'gram', preparation: 'crudo' },
  { matches: ['chorizo de soya', 'chorizo de soja'], nameEn: 'Soy Chorizo', protein: 20, fat: 3, carbs: 20, sugar: 2, fiber: 10, calories: 180, measureType: 'gram', preparation: 'crudo' },
  { matches: ['harina de gluten', 'gluten', 'vital wheat gluten'], nameEn: 'Vital Wheat Gluten', protein: 75, fat: 6, carbs: 14, sugar: 0, fiber: 1, calories: 370, measureType: 'gram', preparation: 'crudo' },
  { matches: ['proteina en polvo', 'proteína en polvo', 'whey'], nameEn: 'Protein Powder', protein: 80, fat: 5, carbs: 8, sugar: 2, fiber: 1, calories: 380, measureType: 'gram', preparation: 'crudo' },
  { matches: ['soya texturizada'], nameEn: 'Textured Soy', protein: 52, fat: 1, carbs: 33, sugar: 0, fiber: 13, calories: 290, measureType: 'gram', preparation: 'crudo' },
  { matches: ['tofu'], nameEn: 'Tofu', protein: 8, fat: 4, carbs: 2, sugar: 0.5, fiber: 0.5, calories: 76, measureType: 'gram', preparation: 'crudo' },
  { matches: ['pollo', 'pechuga'], nameEn: 'Chicken', protein: 31, fat: 3.6, carbs: 0, sugar: 0, fiber: 0, calories: 165, measureType: 'gram', preparation: 'crudo' },

  { matches: ['frijol', 'frijoles'], nameEn: 'Beans', protein: 21, fat: 1.2, carbs: 63, sugar: 2, fiber: 15, calories: 347, measureType: 'gram', preparation: 'cocido' },
  { matches: ['lentejas'], nameEn: 'Lentils', protein: 25, fat: 1.1, carbs: 60, sugar: 2, fiber: 11, calories: 353, measureType: 'gram', preparation: 'cocido' },
  { matches: ['garbanzo'], nameEn: 'Chickpea', protein: 19, fat: 6, carbs: 61, sugar: 11, fiber: 17, calories: 364, measureType: 'gram', preparation: 'cocido' },
  { matches: ['quinoa'], nameEn: 'Quinoa', protein: 14, fat: 6, carbs: 64, sugar: 0, fiber: 7, calories: 368, measureType: 'gram', preparation: 'cocido' },
  { matches: ['edamames', 'edamame'], nameEn: 'Edamame', protein: 12, fat: 5, carbs: 9, sugar: 3, fiber: 5, calories: 121, measureType: 'gram', preparation: 'cocido' },
  { matches: ['cacahuate'], nameEn: 'Peanuts', protein: 26, fat: 49, carbs: 16, sugar: 4, fiber: 9, calories: 567, measureType: 'gram', preparation: 'cocido' },
  { matches: ['arroz integral', 'arroz jazmin', 'arroz', 'arroz cocido'], nameEn: 'Rice', protein: 2.6, fat: 0.3, carbs: 28, sugar: 0.1, fiber: 0.4, calories: 130, measureType: 'gram', preparation: 'cocido' },
  { matches: ['avena integral', 'avena', 'avena en hojuelas'], nameEn: 'Oats', protein: 13.5, fat: 6.5, carbs: 66, sugar: 1, fiber: 10, calories: 379, measureType: 'gram', preparation: 'cocido' },
  { matches: ['harina de avena'], nameEn: 'Oat Flour', protein: 13, fat: 7, carbs: 66, sugar: 1, fiber: 10, calories: 390, measureType: 'gram', preparation: 'cocido' },
  { matches: ['amaranto'], nameEn: 'Amaranth', protein: 4, fat: 0.7, carbs: 19, sugar: 0.5, fiber: 2, calories: 103, measureType: 'gram', preparation: 'cocido' },
  { matches: ['cuscus', 'cuscús'], nameEn: 'Couscous', protein: 4, fat: 0.2, carbs: 23, sugar: 0.5, fiber: 1.4, calories: 112, measureType: 'gram', preparation: 'cocido' },
  { matches: ['pan blanco'], nameEn: 'White Bread', protein: 9, fat: 3, carbs: 49, sugar: 5, fiber: 3, calories: 265, measureType: 'gram', preparation: 'cocido' },
  { matches: ['pan integral'], nameEn: 'Whole Wheat Bread', protein: 13, fat: 3.5, carbs: 41, sugar: 6, fiber: 7, calories: 247, measureType: 'gram', preparation: 'cocido' },
  { matches: ['pan de caja', 'pan bimbo', 'pan para sandwich'], nameEn: 'Sliced Bread', protein: 8, fat: 3, carbs: 50, sugar: 6, fiber: 2, calories: 265, measureType: 'gram', preparation: 'cocido' },
  { matches: ['baguette'], nameEn: 'Baguette', protein: 9, fat: 1.5, carbs: 55, sugar: 2, fiber: 2, calories: 270, measureType: 'gram', preparation: 'cocido' },
  { matches: ['pan pita'], nameEn: 'Pita Bread', protein: 9, fat: 1.2, carbs: 55, sugar: 1.5, fiber: 2.2, calories: 262, measureType: 'gram', preparation: 'cocido' },
  { matches: ['croissant'], nameEn: 'Croissant', protein: 8, fat: 21, carbs: 45, sugar: 8, fiber: 2, calories: 406, measureType: 'gram', preparation: 'cocido' },
  { matches: ['muffin'], nameEn: 'Muffin', protein: 5, fat: 12, carbs: 55, sugar: 25, fiber: 1.5, calories: 340, measureType: 'gram', preparation: 'cocido' },
  { matches: ['galleta salada'], nameEn: 'Cracker', protein: 7, fat: 17, carbs: 67, sugar: 3, fiber: 2, calories: 421, measureType: 'gram', preparation: 'cocido' },
  { matches: ['galleta dulce', 'galleta de chocolate'], nameEn: 'Cookie', protein: 5, fat: 20, carbs: 65, sugar: 30, fiber: 2, calories: 460, measureType: 'gram', preparation: 'cocido' },
  { matches: ['cereal'], nameEn: 'Cereal', protein: 7, fat: 2, carbs: 80, sugar: 20, fiber: 5, calories: 350, measureType: 'gram', preparation: 'cocido' },
  { matches: ['granola'], nameEn: 'Granola', protein: 10, fat: 20, carbs: 55, sugar: 15, fiber: 7, calories: 420, measureType: 'gram', preparation: 'cocido' },
  { matches: ['panqueque', 'pancake'], nameEn: 'Pancake', protein: 6, fat: 10, carbs: 40, sugar: 8, fiber: 1, calories: 290, measureType: 'gram', preparation: 'cocido' },
  { matches: ['waffle'], nameEn: 'Waffle', protein: 6, fat: 12, carbs: 45, sugar: 10, fiber: 1.5, calories: 310, measureType: 'gram', preparation: 'cocido' },
  { matches: ['pasta cocida', 'pasta'], nameEn: 'Cooked Pasta', protein: 5, fat: 0.5, carbs: 25, sugar: 0.5, fiber: 1.5, calories: 112, measureType: 'gram', preparation: 'cocido' },
  { matches: ['fideos', 'fideo'], nameEn: 'Noodles', protein: 5, fat: 0.5, carbs: 25, sugar: 0.5, fiber: 1.5, calories: 112, measureType: 'gram', preparation: 'cocido' },
  { matches: ['tortilla de harina', 'tortilla de trigo'], nameEn: 'Flour Tortilla', protein: 9, fat: 7, carbs: 50, sugar: 2, fiber: 2, calories: 304, measureType: 'gram', preparation: 'cocido' },
  { matches: ['arepa'], nameEn: 'Arepa', protein: 5, fat: 2, carbs: 37, sugar: 1, fiber: 3, calories: 185, measureType: 'unit', unitName: 'arepa', unitGrams: 100, preparation: 'cocido' },
  { matches: ['tamal', 'tamales'], nameEn: 'Tamale', protein: 6, fat: 11, carbs: 30, sugar: 1, fiber: 4, calories: 240, measureType: 'unit', unitName: 'tamal', unitGrams: 150, preparation: 'cocido' },
  { matches: ['empanada', 'empanadas'], nameEn: 'Empanada', protein: 8, fat: 15, carbs: 35, sugar: 2, fiber: 2, calories: 320, measureType: 'unit', unitName: 'empanada', unitGrams: 100, preparation: 'cocido' },
  { matches: ['elote', 'maiz', 'maíz'], nameEn: 'Corn', protein: 3.2, fat: 1.2, carbs: 19, sugar: 6, fiber: 2.7, calories: 86, measureType: 'gram', preparation: 'cocido' },
  { matches: ['yuca', 'mandioca'], nameEn: 'Cassava', protein: 1.4, fat: 0.3, carbs: 38, sugar: 1.7, fiber: 1.8, calories: 159, measureType: 'gram', preparation: 'cocido' },
  { matches: ['harina de trigo'], nameEn: 'Wheat Flour', protein: 10, fat: 1, carbs: 76, sugar: 0.3, fiber: 2.7, calories: 364, measureType: 'gram', preparation: 'cocido' },
  { matches: ['azucar', 'azúcar'], nameEn: 'Sugar', protein: 0, fat: 0, carbs: 100, sugar: 100, fiber: 0, calories: 387, measureType: 'gram' },
  { matches: ['miel'], nameEn: 'Honey', protein: 0.4, fat: 0, carbs: 82, sugar: 82, fiber: 0.2, calories: 304, measureType: 'gram' },
  { matches: ['mermelada'], nameEn: 'Jam', protein: 0.5, fat: 0.1, carbs: 65, sugar: 48, fiber: 1, calories: 250, measureType: 'gram' },
  { matches: ['datil', 'dátil'], nameEn: 'Date', protein: 2.5, fat: 0.4, carbs: 75, sugar: 63, fiber: 8, calories: 282, measureType: 'gram' },
  { matches: ['palomitas de maiz', 'palomitas de maíz', 'popcorn'], nameEn: 'Popcorn', protein: 13, fat: 4.5, carbs: 78, sugar: 0.9, fiber: 15, calories: 387, measureType: 'gram', preparation: 'cocido' },
  { matches: ['papas fritas', 'papas chips'], nameEn: 'Potato Chips', protein: 4, fat: 35, carbs: 53, sugar: 0.3, fiber: 4, calories: 536, measureType: 'gram', preparation: 'cocido' },
  { matches: ['tortilla de nopal'], nameEn: 'Nopal Tortilla', protein: 2, fat: 1, carbs: 15, sugar: 0, fiber: 3, calories: 80, measureType: 'unit', unitName: 'tortilla', unitGrams: 40, preparation: 'cocido' },
  { matches: ['tortilla de nixtamal'], nameEn: 'Corn Tortilla', protein: 2.5, fat: 0.5, carbs: 22, sugar: 0.5, fiber: 3, calories: 105, measureType: 'unit', unitName: 'tortilla', unitGrams: 45, preparation: 'cocido' },
  { matches: ['papa', 'papas'], nameEn: 'Potato', protein: 2, fat: 0.1, carbs: 20, sugar: 1, fiber: 2, calories: 87, measureType: 'gram', preparation: 'cocido' },
  { matches: ['camote', 'batata'], nameEn: 'Sweet Potato', protein: 1.6, fat: 0.1, carbs: 20, sugar: 6, fiber: 3, calories: 86, measureType: 'gram', preparation: 'cocido' },

  { matches: ['aceite de aguacate'], nameEn: 'Avocado Oil', protein: 0, fat: 100, carbs: 0, sugar: 0, fiber: 0, calories: 884, measureType: 'gram' },
  { matches: ['aceite de oliva'], nameEn: 'Olive Oil', protein: 0, fat: 100, carbs: 0, sugar: 0, fiber: 0, calories: 884, measureType: 'gram' },
  { matches: ['aceite de coco'], nameEn: 'Coconut Oil', protein: 0, fat: 100, carbs: 0, sugar: 0, fiber: 0, calories: 884, measureType: 'gram' },
  { matches: ['aceite de girasol'], nameEn: 'Sunflower Oil', protein: 0, fat: 100, carbs: 0, sugar: 0, fiber: 0, calories: 884, measureType: 'gram' },
  { matches: ['aceite de canola'], nameEn: 'Canola Oil', protein: 0, fat: 100, carbs: 0, sugar: 0, fiber: 0, calories: 884, measureType: 'gram' },
  { matches: ['aceite de sesamo', 'aceite de sésamo'], nameEn: 'Sesame Oil', protein: 0, fat: 100, carbs: 0, sugar: 0, fiber: 0, calories: 884, measureType: 'gram' },
  { matches: ['mantequilla'], nameEn: 'Butter', protein: 1, fat: 81, carbs: 0.1, sugar: 0, fiber: 0, calories: 717, measureType: 'gram' },
  { matches: ['mantequilla de mani', 'mantequilla de maní', 'mantequilla de cacahuate'], nameEn: 'Peanut Butter', protein: 25, fat: 50, carbs: 20, sugar: 9, fiber: 6, calories: 588, measureType: 'gram' },
  { matches: ['mantequilla de almendra'], nameEn: 'Almond Butter', protein: 21, fat: 56, carbs: 19, sugar: 5, fiber: 10, calories: 614, measureType: 'gram' },
  { matches: ['mayonesa'], nameEn: 'Mayonnaise', protein: 1, fat: 75, carbs: 1, sugar: 1, fiber: 0, calories: 680, measureType: 'gram' },
  { matches: ['crema agria', 'crema'], nameEn: 'Sour Cream', protein: 3, fat: 20, carbs: 5, sugar: 0.3, fiber: 0, calories: 198, measureType: 'gram' },
  { matches: ['queso crema'], nameEn: 'Cream Cheese', protein: 6, fat: 34, carbs: 4, sugar: 3, fiber: 0, calories: 342, measureType: 'gram' },
  { matches: ['queso parmesano', 'parmesano'], nameEn: 'Parmesan', protein: 35, fat: 25, carbs: 3, sugar: 0, fiber: 0, calories: 420, measureType: 'gram' },
  { matches: ['queso cheddar', 'cheddar'], nameEn: 'Cheddar', protein: 25, fat: 33, carbs: 1, sugar: 0.5, fiber: 0, calories: 403, measureType: 'gram' },
  { matches: ['queso feta', 'feta'], nameEn: 'Feta', protein: 14, fat: 21, carbs: 4, sugar: 4, fiber: 0, calories: 264, measureType: 'gram' },
  { matches: ['hummus'], nameEn: 'Hummus', protein: 8, fat: 9, carbs: 14, sugar: 0, fiber: 6, calories: 166, measureType: 'gram' },
  { matches: ['pesto'], nameEn: 'Pesto', protein: 4, fat: 45, carbs: 4, sugar: 0.9, fiber: 2, calories: 426, measureType: 'gram' },
  { matches: ['aceitunas'], nameEn: 'Olives', protein: 1, fat: 11, carbs: 6, sugar: 0, fiber: 3, calories: 145, measureType: 'gram' },
  { matches: ['nueces'], nameEn: 'Walnuts', protein: 15, fat: 65, carbs: 14, sugar: 2.6, fiber: 7, calories: 654, measureType: 'gram' },
  { matches: ['almendras'], nameEn: 'Almonds', protein: 21, fat: 50, carbs: 22, sugar: 4, fiber: 13, calories: 579, measureType: 'gram' },
  { matches: ['anacardos', 'cashews'], nameEn: 'Cashews', protein: 18, fat: 44, carbs: 30, sugar: 6, fiber: 3, calories: 553, measureType: 'gram' },
  { matches: ['pistachos'], nameEn: 'Pistachios', protein: 20, fat: 45, carbs: 28, sugar: 7, fiber: 10, calories: 560, measureType: 'gram' },
  { matches: ['semillas de girasol'], nameEn: 'Sunflower Seeds', protein: 21, fat: 51, carbs: 20, sugar: 2.6, fiber: 9, calories: 584, measureType: 'gram' },
  { matches: ['semillas de calabaza'], nameEn: 'Pumpkin Seeds', protein: 30, fat: 49, carbs: 11, sugar: 1.4, fiber: 6, calories: 559, measureType: 'gram' },
  { matches: ['chia'], nameEn: 'Chia', protein: 17, fat: 31, carbs: 42, sugar: 0, fiber: 34, calories: 486, measureType: 'gram' },
  { matches: ['linaza'], nameEn: 'Flaxseed', protein: 18, fat: 42, carbs: 29, sugar: 0, fiber: 27, calories: 534, measureType: 'gram' },
  { matches: ['ghee'], nameEn: 'Ghee', protein: 0, fat: 99, carbs: 0, sugar: 0, fiber: 0, calories: 876, measureType: 'gram' },
  { matches: ['sesamo', 'ajonjolí'], nameEn: 'Sesame', protein: 18, fat: 50, carbs: 23, sugar: 0.5, fiber: 12, calories: 573, measureType: 'gram' },
  { matches: ['manteca de cerdo'], nameEn: 'Lard', protein: 0, fat: 100, carbs: 0, sugar: 0, fiber: 0, calories: 902, measureType: 'gram' },
  { matches: ['queso de cabra'], nameEn: 'Goat Cheese', protein: 21, fat: 30, carbs: 0, sugar: 0, fiber: 0, calories: 364, measureType: 'gram' },
  { matches: ['queso mozarella', 'mozarella'], nameEn: 'Mozzarella', protein: 22, fat: 22, carbs: 2.2, sugar: 1, fiber: 0, calories: 300, measureType: 'gram' },

  { matches: ['platano macho', 'plátano macho', 'platano', 'plátano', 'banano'], nameEn: 'Plantain', protein: 1.1, fat: 0.3, carbs: 23, sugar: 12, fiber: 2.6, calories: 96, measureType: 'gram' },
  { matches: ['aguacate'], nameEn: 'Avocado', protein: 2, fat: 15, carbs: 9, sugar: 0.7, fiber: 6.7, calories: 160, measureType: 'gram' },
  { matches: ['mango'], nameEn: 'Mango', protein: 0.8, fat: 0.4, carbs: 15, sugar: 14, fiber: 1.6, calories: 60, measureType: 'gram' },
  { matches: ['papaya'], nameEn: 'Papaya', protein: 0.5, fat: 0.1, carbs: 11, sugar: 8, fiber: 1.7, calories: 43, measureType: 'gram' },
  { matches: ['frutos rojos', 'berries'], nameEn: 'Berries', protein: 0.7, fat: 0.3, carbs: 12, sugar: 5, fiber: 3, calories: 53, measureType: 'gram' },
  { matches: ['manzana verde'], nameEn: 'Green Apple', protein: 0.3, fat: 0.2, carbs: 14, sugar: 10, fiber: 2.5, calories: 58, measureType: 'gram' },
  { matches: ['piña'], nameEn: 'Pineapple', protein: 0.5, fat: 0.1, carbs: 13, sugar: 10, fiber: 1.4, calories: 50, measureType: 'gram' },
  { matches: ['sandia', 'sandía'], nameEn: 'Watermelon', protein: 0.6, fat: 0.2, carbs: 8, sugar: 6, fiber: 0.4, calories: 30, measureType: 'gram' },
  { matches: ['manzana'], nameEn: 'Apple', protein: 0.3, fat: 0.2, carbs: 14, sugar: 10, fiber: 2.4, calories: 52, measureType: 'gram' },
  { matches: ['pera'], nameEn: 'Pear', protein: 0.4, fat: 0.1, carbs: 15, sugar: 10, fiber: 3.1, calories: 57, measureType: 'gram' },
  { matches: ['naranja'], nameEn: 'Orange', protein: 0.9, fat: 0.1, carbs: 12, sugar: 9, fiber: 2.4, calories: 47, measureType: 'gram' },
  { matches: ['mandarina'], nameEn: 'Tangerine', protein: 0.8, fat: 0.3, carbs: 13, sugar: 11, fiber: 1.8, calories: 53, measureType: 'gram' },
  { matches: ['limon', 'limón'], nameEn: 'Lemon', protein: 1.1, fat: 0.3, carbs: 9, sugar: 2.5, fiber: 2.8, calories: 29, measureType: 'gram' },
  { matches: ['lima'], nameEn: 'Lime', protein: 0.7, fat: 0.2, carbs: 11, sugar: 2, fiber: 3, calories: 30, measureType: 'gram' },
  { matches: ['toronja', 'pomelo'], nameEn: 'Grapefruit', protein: 0.8, fat: 0.1, carbs: 11, sugar: 7, fiber: 1.6, calories: 42, measureType: 'gram' },
  { matches: ['kiwi'], nameEn: 'Kiwi', protein: 1.1, fat: 0.5, carbs: 15, sugar: 9, fiber: 3, calories: 61, measureType: 'gram' },
  { matches: ['uva'], nameEn: 'Grape', protein: 0.7, fat: 0.4, carbs: 18, sugar: 16, fiber: 0.9, calories: 69, measureType: 'gram' },
  { matches: ['fresa', 'fresas'], nameEn: 'Strawberry', protein: 0.7, fat: 0.3, carbs: 8, sugar: 4.9, fiber: 2, calories: 32, measureType: 'gram' },
  { matches: ['frambuesa', 'frambuesas'], nameEn: 'Raspberry', protein: 1.2, fat: 0.7, carbs: 12, sugar: 4.4, fiber: 6.5, calories: 52, measureType: 'gram' },
  { matches: ['arandano', 'arándano', 'arandanos', 'arándanos'], nameEn: 'Blueberry', protein: 0.7, fat: 0.3, carbs: 14, sugar: 10, fiber: 2.4, calories: 57, measureType: 'gram' },
  { matches: ['mora', 'moras'], nameEn: 'Blackberry', protein: 1.4, fat: 0.4, carbs: 10, sugar: 4.9, fiber: 5.3, calories: 43, measureType: 'gram' },
  { matches: ['cereza', 'cerezas'], nameEn: 'Cherry', protein: 1.1, fat: 0.2, carbs: 16, sugar: 13, fiber: 2.1, calories: 63, measureType: 'gram' },
  { matches: ['durazno'], nameEn: 'Peach', protein: 0.9, fat: 0.3, carbs: 10, sugar: 8, fiber: 1.5, calories: 39, measureType: 'gram' },
  { matches: ['ciruela'], nameEn: 'Plum', protein: 0.7, fat: 0.3, carbs: 11, sugar: 10, fiber: 1.4, calories: 46, measureType: 'gram' },
  { matches: ['albaricoque', 'chabacano'], nameEn: 'Apricot', protein: 1.4, fat: 0.4, carbs: 11, sugar: 9, fiber: 2, calories: 48, measureType: 'gram' },
  { matches: ['melon', 'melón'], nameEn: 'Melon', protein: 0.8, fat: 0.2, carbs: 8, sugar: 8, fiber: 0.9, calories: 34, measureType: 'gram' },
  { matches: ['higo'], nameEn: 'Fig', protein: 0.8, fat: 0.3, carbs: 19, sugar: 16, fiber: 2.9, calories: 74, measureType: 'gram' },
  { matches: ['granada'], nameEn: 'Pomegranate', protein: 1.7, fat: 1.2, carbs: 19, sugar: 14, fiber: 4, calories: 83, measureType: 'gram' },
  { matches: ['maracuya', 'maracuyá', 'parcha'], nameEn: 'Passion Fruit', protein: 2.2, fat: 0.7, carbs: 23, sugar: 11, fiber: 10, calories: 97, measureType: 'gram' },
  { matches: ['guayaba'], nameEn: 'Guava', protein: 2.6, fat: 1, carbs: 14, sugar: 9, fiber: 5.4, calories: 68, measureType: 'gram' },
  { matches: ['coco'], nameEn: 'Coconut', protein: 3.3, fat: 33.5, carbs: 15, sugar: 6, fiber: 9, calories: 354, measureType: 'gram' },

  { matches: ['brocoli', 'brócoli'], nameEn: 'Broccoli', protein: 2.8, fat: 0.4, carbs: 7, sugar: 1.7, fiber: 2.6, calories: 34, measureType: 'gram' },
  { matches: ['coliflor'], nameEn: 'Cauliflower', protein: 1.9, fat: 0.3, carbs: 5, sugar: 2, fiber: 2, calories: 25, measureType: 'gram' },
  { matches: ['kale'], nameEn: 'Kale', protein: 4.3, fat: 0.9, carbs: 9, sugar: 0.9, fiber: 3.6, calories: 49, measureType: 'gram' },
  { matches: ['arugula', 'rúcula'], nameEn: 'Arugula', protein: 2.6, fat: 0.7, carbs: 3.7, sugar: 1, fiber: 1.5, calories: 25, measureType: 'gram' },
  { matches: ['pepino'], nameEn: 'Cucumber', protein: 0.7, fat: 0.1, carbs: 3.6, sugar: 1.7, fiber: 0.5, calories: 15, measureType: 'gram' },
  { matches: ['cilantro', 'cilantr'], nameEn: 'Cilantro', protein: 2.1, fat: 0.5, carbs: 3.7, sugar: 0.9, fiber: 2.8, calories: 23, measureType: 'gram' },
  { matches: ['champiñon', 'champiñones', 'hongo'], nameEn: 'Mushroom', protein: 3.1, fat: 0.3, carbs: 3.3, sugar: 1.7, fiber: 1, calories: 22, measureType: 'gram' },
  { matches: ['tomate', 'jitomate'], nameEn: 'Tomato', protein: 0.9, fat: 0.2, carbs: 3.9, sugar: 2.6, fiber: 1.2, calories: 18, measureType: 'gram' },
  { matches: ['zanahoria'], nameEn: 'Carrot', protein: 0.9, fat: 0.2, carbs: 10, sugar: 4.7, fiber: 2.8, calories: 41, measureType: 'gram' },
  { matches: ['ajo'], nameEn: 'Garlic', protein: 6.4, fat: 0.5, carbs: 33, sugar: 1, fiber: 2.1, calories: 149, measureType: 'gram' },
  { matches: ['cebolla'], nameEn: 'Onion', protein: 1.1, fat: 0.1, carbs: 9, sugar: 4, fiber: 1.7, calories: 40, measureType: 'gram' },
  { matches: ['pimiento', 'pimiento morron'], nameEn: 'Bell Pepper', protein: 1, fat: 0.3, carbs: 6, sugar: 2.5, fiber: 2, calories: 26, measureType: 'gram' },
  { matches: ['chiles', 'chile'], nameEn: 'Chili', protein: 1.9, fat: 0.4, carbs: 4.6, sugar: 2.5, fiber: 1.5, calories: 20, measureType: 'gram' },
  { matches: ['calabaza'], nameEn: 'Squash', protein: 1.1, fat: 0.1, carbs: 7, sugar: 3, fiber: 1, calories: 26, measureType: 'gram' },
  { matches: ['repollo', 'col'], nameEn: 'Cabbage', protein: 1.3, fat: 0.1, carbs: 6, sugar: 3, fiber: 2.5, calories: 25, measureType: 'gram' },
  { matches: ['esparrago', 'espárrago'], nameEn: 'Asparagus', protein: 2.2, fat: 0.2, carbs: 4, sugar: 2, fiber: 2, calories: 20, measureType: 'gram' },
  { matches: ['tomatillo'], nameEn: 'Tomatillo', protein: 0.9, fat: 0.3, carbs: 6, sugar: 3, fiber: 1.5, calories: 32, measureType: 'gram' },
  { matches: ['cebollin', 'cebollín'], nameEn: 'Chives', protein: 3.3, fat: 0.7, carbs: 7, sugar: 1.5, fiber: 2.6, calories: 30, measureType: 'gram' },
  { matches: ['puerro'], nameEn: 'Leek', protein: 1.5, fat: 0.3, carbs: 14, sugar: 3, fiber: 1.8, calories: 61, measureType: 'gram' },
  { matches: ['lechuga'], nameEn: 'Lettuce', protein: 1.4, fat: 0.2, carbs: 3, sugar: 1.8, fiber: 1.3, calories: 15, measureType: 'gram' },
  { matches: ['espinaca'], nameEn: 'Spinach', protein: 2.9, fat: 0.4, carbs: 3.6, sugar: 0.4, fiber: 2.2, calories: 23, measureType: 'gram' },
  { matches: ['apio'], nameEn: 'Celery', protein: 0.7, fat: 0.2, carbs: 3, sugar: 1.3, fiber: 1.6, calories: 14, measureType: 'gram' },
  { matches: ['remolacha', 'betabel'], nameEn: 'Beet', protein: 1.6, fat: 0.2, carbs: 10, sugar: 7, fiber: 2.8, calories: 43, measureType: 'gram' },
  { matches: ['calabacin', 'calabacín'], nameEn: 'Zucchini', protein: 1.2, fat: 0.3, carbs: 3.1, sugar: 2.5, fiber: 1, calories: 17, measureType: 'gram' },
  { matches: ['berenjena'], nameEn: 'Eggplant', protein: 1, fat: 0.2, carbs: 6, sugar: 3.5, fiber: 3, calories: 25, measureType: 'gram' },
  { matches: ['ejote', 'ejotes', 'judia verde', 'judía verde'], nameEn: 'Green Beans', protein: 1.8, fat: 0.1, carbs: 7, sugar: 1.5, fiber: 2.7, calories: 31, measureType: 'gram' },
  { matches: ['chicharo', 'chícharo', 'guisante'], nameEn: 'Peas', protein: 5.4, fat: 0.4, carbs: 14, sugar: 6, fiber: 5.7, calories: 81, measureType: 'gram' },
  { matches: ['haba', 'habas'], nameEn: 'Fava Beans', protein: 7.6, fat: 0.4, carbs: 18, sugar: 5, fiber: 7.5, calories: 110, measureType: 'gram' },
  { matches: ['col de bruselas'], nameEn: 'Brussels Sprouts', protein: 3.4, fat: 0.4, carbs: 9, sugar: 2.2, fiber: 3.8, calories: 43, measureType: 'gram' },
  { matches: ['acelga'], nameEn: 'Chard', protein: 1.8, fat: 0.2, carbs: 3.7, sugar: 1.1, fiber: 1.6, calories: 19, measureType: 'gram' },
  { matches: ['rabano', 'rábano'], nameEn: 'Radish', protein: 0.7, fat: 0.1, carbs: 4, sugar: 2, fiber: 1.6, calories: 16, measureType: 'gram' },
  { matches: ['nabo'], nameEn: 'Turnip', protein: 0.9, fat: 0.1, carbs: 6, sugar: 3.8, fiber: 1.8, calories: 28, measureType: 'gram' },
  { matches: ['alcachofa', 'alcachofas'], nameEn: 'Artichoke', protein: 3.3, fat: 0.2, carbs: 12, sugar: 1.3, fiber: 5.4, calories: 47, measureType: 'gram' },
  { matches: ['palmito'], nameEn: 'Hearts of Palm', protein: 2.6, fat: 0.2, carbs: 5, sugar: 0, fiber: 2.4, calories: 28, measureType: 'gram' },
  { matches: ['hinojo'], nameEn: 'Fennel', protein: 1.2, fat: 0.2, carbs: 7, sugar: 3.9, fiber: 3.1, calories: 31, measureType: 'gram' },
  { matches: ['berros'], nameEn: 'Watercress', protein: 2.3, fat: 0.4, carbs: 4.4, sugar: 0.2, fiber: 2.6, calories: 30, measureType: 'gram' },
  { matches: ['bok choy'], nameEn: 'Bok Choy', protein: 1.5, fat: 0.2, carbs: 2.2, sugar: 1, fiber: 1, calories: 13, measureType: 'gram' },
  { matches: ['jicama', 'jícama'], nameEn: 'Jícama', protein: 0.7, fat: 0.1, carbs: 9, sugar: 1.8, fiber: 4.5, calories: 38, measureType: 'gram' },
  { matches: ['repollo morado'], nameEn: 'Red Cabbage', protein: 1.4, fat: 0.2, carbs: 7, sugar: 3.8, fiber: 2.1, calories: 31, measureType: 'gram' },

  { matches: ['curcuma', 'cúrcuma'], nameEn: 'Turmeric', protein: 8, fat: 10, carbs: 65, sugar: 3, fiber: 21, calories: 354, measureType: 'gram' },
  { matches: ['jengibre'], nameEn: 'Ginger', protein: 1.8, fat: 0.8, carbs: 18, sugar: 1.7, fiber: 2, calories: 80, measureType: 'gram' },
  { matches: ['canela'], nameEn: 'Cinnamon', protein: 4, fat: 1.2, carbs: 80, sugar: 2, fiber: 53, calories: 247, measureType: 'gram' },
  { matches: ['ajo en polvo'], nameEn: 'Garlic Powder', protein: 16, fat: 0.7, carbs: 73, sugar: 2, fiber: 7, calories: 331, measureType: 'gram' },
  { matches: ['cebolla en polvo'], nameEn: 'Onion Powder', protein: 10, fat: 0.7, carbs: 79, sugar: 8, fiber: 11, calories: 341, measureType: 'gram' },
  { matches: ['oregano', 'orégano'], nameEn: 'Oregano', protein: 9, fat: 4.3, carbs: 69, sugar: 4, fiber: 38, calories: 265, measureType: 'gram' },
  { matches: ['sal de mar', 'sal'], nameEn: 'Salt', protein: 0, fat: 0, carbs: 0, sugar: 0, fiber: 0, calories: 0, measureType: 'gram' },
  { matches: ['limón en polvo'], nameEn: 'Lemon Powder', protein: 0, fat: 0, carbs: 0, sugar: 0, fiber: 0, calories: 0, measureType: 'gram' },
  { matches: ['clavo de olor'], nameEn: 'Clove', protein: 6, fat: 20, carbs: 66, sugar: 2, fiber: 32, calories: 323, measureType: 'gram' },
  { matches: ['romero'], nameEn: 'Rosemary', protein: 3.3, fat: 5.9, carbs: 64, sugar: 0, fiber: 0, calories: 131, measureType: 'gram' },
  { matches: ['tomillo'], nameEn: 'Thyme', protein: 5.6, fat: 1.7, carbs: 65, sugar: 0, fiber: 0, calories: 276, measureType: 'gram' },
  { matches: ['comino'], nameEn: 'Cumin', protein: 18, fat: 22, carbs: 44, sugar: 0, fiber: 10, calories: 375, measureType: 'gram' },
  { matches: ['paprika'], nameEn: 'Paprika', protein: 14, fat: 13, carbs: 54, sugar: 0, fiber: 0, calories: 282, measureType: 'gram' },
  { matches: ['laurel'], nameEn: 'Bay Leaf', protein: 7.6, fat: 8.4, carbs: 75, sugar: 0, fiber: 0, calories: 313, measureType: 'gram' },
  { matches: ['cacao'], nameEn: 'Cacao', protein: 20, fat: 23, carbs: 58, sugar: 1, fiber: 30, calories: 504, measureType: 'gram' },
  { matches: ['levadura nutricional'], nameEn: 'Nutritional Yeast', protein: 50, fat: 5, carbs: 35, sugar: 0, fiber: 0, calories: 400, measureType: 'gram' },
  { matches: ['extracto de vainilla'], nameEn: 'Vanilla Extract', protein: 0, fat: 0, carbs: 0, sugar: 0, fiber: 0, calories: 0, measureType: 'gram' },
  { matches: ['psyllum husk', 'psyllium'], nameEn: 'Psyllium Husk', protein: 0, fat: 0, carbs: 80, sugar: 0, fiber: 70, calories: 200, measureType: 'gram' },
  { matches: ['eritritol'], nameEn: 'Erythritol', protein: 0, fat: 0, carbs: 0, sugar: 0, fiber: 0, calories: 0, measureType: 'gram' },

  { matches: ['glicinato de magnesio', 'magnesio'], nameEn: 'Magnesium Glycinate', protein: 0, fat: 0, carbs: 0, sugar: 0, fiber: 0, calories: 0, measureType: 'unit', unitName: 'cápsula', unitGrams: 0 },
  { matches: ['vitamina d3', 'vitamina d', 'd3+k2'], nameEn: 'Vitamin D3', protein: 0, fat: 0, carbs: 0, sugar: 0, fiber: 0, calories: 0, measureType: 'unit', unitName: 'gota', unitGrams: 0 },
  { matches: ['omega 3'], nameEn: 'Omega 3', protein: 0, fat: 0, carbs: 0, sugar: 0, fiber: 0, calories: 0, measureType: 'unit', unitName: 'cápsula', unitGrams: 0 },
  { matches: ['l-leanina', 'l teanina'], nameEn: 'L-Theanine', protein: 0, fat: 0, carbs: 0, sugar: 0, fiber: 0, calories: 0, measureType: 'unit', unitName: 'cápsula', unitGrams: 0 },
  { matches: ['ashwagandha'], nameEn: 'Ashwagandha', protein: 0, fat: 0, carbs: 0, sugar: 0, fiber: 0, calories: 0, measureType: 'unit', unitName: 'cápsula', unitGrams: 0 },
  { matches: ['probioticos', 'probióticos'], nameEn: 'Probiotics', protein: 0, fat: 0, carbs: 0, sugar: 0, fiber: 0, calories: 0, measureType: 'unit', unitName: 'cápsula', unitGrams: 0 },
  { matches: ['vitamina c'], nameEn: 'Vitamin C', protein: 0, fat: 0, carbs: 0, sugar: 0, fiber: 0, calories: 0, measureType: 'unit', unitName: 'tableta', unitGrams: 0 },
]
